### ISSUE TITLE
Namespace gets ignored

### ISSUE THREAD

**Issue by niekappartmedia** [Azure/k8s-create-secret#1]
I have the following problem:
When i add a secret to an existing namespace in the cluster: /usr/bin/kubectl create secret generic mysql-secret --from-literal=MYSQL_DATABASE=*** --from-literal=MYSQL_USERNAME=*** -- from-literal=MYSQL_PASSWORD=*** -n magento-test-develop

It adds the secret to the default namespace but the custom namespace is there. And the expected behaviour should be that it adds the secret to the namespace given.

**Comment by niekappartmedia** [comment]
After some research this seems more like a kubernetes bug/wrong behaviour because the command is sending the namespace correctly with the kubectl command.

**Comment by tomwatson-tdy** [comment]
Did you manage to find a fix for this?

**Comment by tomwatson-tdy** [comment]
In the event someone else encounters this problem,  I think I _might_ have figured out the offending issue.

If an email isn't provided, one gets substituted in with a single space, and the namespace parameter gets added in afterwards, having extra whitespace shouldn't affect things (doesn't when I test locally), but specifying the email parameter as `''` appears to have fixed the issue for me.
