### ISSUE TITLE
Create secret action is failing randomly upon re-running the workflow.

### ISSUE THREAD

**Issue by anuragc617** [Azure/k8s-create-secret#2]
The create secret action is failing randomly upon re-running the workflow with error: 
`Error from server (AlreadyExists): secrets "bugbash1622dockerauth" already exists`

Failed workflow link: https://github.com/anuragc617/acr-build-helloworld-node/runs/450381384#step:7:13

**Comment by ds-ms** [comment]
Closing stale issue. Feel free to reopen if it recurs.
