### ISSUE TITLE
Need to use --force for arguments?

### ISSUE THREAD

**Issue by juliakm** [Azure/k8s-create-secret#20]
This [documentation PR](https://github.com/MicrosoftDocs/azure-docs/pull/73598) flagged that you need to now use `arguments: --force true` with the action. Could you please take a look? If this is the new way to implement the action please let me know so that we can approve the PR.

**Comment by ernani** [comment]
I got a warning when using force: true while when using arguments: --force true worked with no warnings hence I have suggested that PR change. Please do let me know if that's not correct.

**Comment by ds-ms** [comment]
This was perhaps a documentation issue; there wasn't support for `force` input in the action.yml  
I've approved the documentation change, @juliakm you can take it forward :)
