### ISSUE TITLE
Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by richardsimko** [Azure/k8s-create-secret#33]
When running 2.0 I get the following error:

```
Run azure/k8s-create-secret@v2
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/azure/k8s-create-secret/v2/lib/run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/azure/k8s-create-secret/v2/lib/run.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/azure/k8s-create-secret/v2/lib/run.js'
  ]
***
```

Based on the diff between 1.1 and 2.0 I would guess you forgot to commit the `node_modules` directory but I could be wrong, I haven't worked that much with custom GH actions.

**Comment by richardsimko** [comment]
@davidgamero Unfortunately 2.0 does not work at all in the current state :(

**Comment by davidgamero** [comment]
thanks for letting me know, I'm investigating now

**Comment by davidgamero** [comment]
just updated release, and it should be resolved. Please let me know if you get it working for your workflow 😄

**Comment by richardsimko** [comment]
Thanks for the quick response! There is a new error now 😅  `Error: Could not find file '/home/runner/work/_actions/_temp_db04e17e-3b1d-4eb1-9730-6d4ec32ab7f8/_staging/Azure-k8s-create-secret-687ece0/node_modules/jest-snapshot/node_modules/.bin/semver'.`

**Comment by davidgamero** [comment]
ahh alright I'll take a look
im going to add the node_modules check into the integration test to avoid this in the future

**Comment by franklinio** [comment]
running into the error when used in gh actions`Unable to resolve action `Azure/k8s-create-secret@v2`, unable to find version `v2``. Not sure if its a related issue

**Comment by davidgamero** [comment]
`v2` tag and release should be linked again now. Still trying to replicate @richardsimko's semver error

**Comment by davidgamero** [comment]
merged updated symlinks. lmk if issue persists

**Comment by iaacautomation** [comment]
Download action repository 'azure/k8s-create-secret@v2' (SHA:7beee6b9d30388057aaf36230b38e921486a752c)
Error: Could not find file '/home/runner/work/_actions/_temp_ffbfc4f2-0c03-4e93-a04c-945f307ecbc9/_staging/Azure-k8s-create-secret-7beee6b/node_modules/jest-snapshot/node_modules/.bin/semver'.

Still there

**Comment by richardsimko** [comment]
@davidgamero I'm also still experiencing the problem as @iaacautomation says.

**Comment by richardsimko** [comment]
Should I open a second bug for this?

**Comment by davidgamero** [comment]
@richardsimko we can keep this one for now I'm taking a look now with @OliverMKing

**Comment by davidgamero** [comment]
i have regenerated the entire release and run a separate test on a manual action which is now passing
no errors on using v2 here, but would appreciate confirmation
https://github.com/davidgamero/k8s-test-action/runs/4694660792?check_suite_focus=true

**Comment by davidgamero** [comment]
closing for now, we can open a new issue if it persists on the newest release

**Comment by richardsimko** [comment]
Thanks, it works now!
