### ISSUE TITLE
Multiple issues with docker-registry secrets

### ISSUE THREAD

**Issue by jryberg** [Azure/k8s-create-secret#75]
I'm getting this warning when creating docker-registry secrets

Warning: Unexpected input(s) 'container-registry-username', 'container-registry-password', valid inputs are ['namespace', 'secret-type', 'secret-name', 'string-data', 'data']

    - name: Set imagePullSecret
      uses: azure/k8s-create-secret@v2
      with:
         namespace: 'somenamespace'
         secret-name: 'somesecretname'
         container-registry-username: ${{ secrets.SOMEUSER }}
         container-registry-password: ${{ secrets.SOMEPASS }}

It should be defined this way according to the documentation and url is optional in the code.

How should this definition look like for a docker-registry secret for Docker Hub? 

The secret is also not created, just deleted
Last lines of the log
```
Deleting secret:
[object Object]
```

**Comment by jryberg** [comment]
Also tried to define container-registry-url: 'docker.io' with the exact same result except it warns about that parameter as well.

This is how the secret looks like when "created" and it does not work
```$ kubectl describe secret somesecretname -n somenamespace
Name:         somesecretname
Namespace:    somenamespace
Labels:       <none>
Annotations:  <none>

Type:  docker-registry

Data
====
```

**Comment by davidgamero** [comment]
Hi @jryberg could you try bumping to v4 and let me know if it works? We reworked how the secret generation works to try to fix this issue in the newer release

**Comment by jryberg** [comment]
Hi @davidgamero , 

Please let me check using version 4 instead of 2.

**Comment by jryberg** [comment]
Yes, it's working with version 4. 

Updated documentation is king 👍
