### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jonas-lomholdt** [Azure/k8s-create-secret#83]
Hi' 

I see a bit of weirdness in the release versions on this action. Will there be a new major version released that has the small fixes and node16 upgrade incorporated?

**Comment by OliverMKing** [comment]
The v4 release should support Node16. What other weirdness do you see?

**Comment by jonas-lomholdt** [comment]
Oh, don't know why it looked messed up on my end. Everything looks fine now :) Sorry for the confusion.
